#!/bin/bash

source config.sh

CONF_FILE=$KERNEL_PATH/.config

if `grep -q 'CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND=y' $CONF_FILE`; then
    sed -i 's/CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND=y/# CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND is not set/g' $CONF_FILE 
    sed -i 's/# CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE is not set/CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE=y/g' $CONF_FILE 
fi
sed -i 's/.*CONFIG_CPU_FREQ_GOV_ONDEMAND.*/CONFIG_CPU_FREQ_GOV_ONDEMAND=m/' $CONF_FILE
